version: 0.2

phases:
  pre_build:
    commands:
      - cd infra/terraform/aws/environments/dev

  build:
    commands:
      - terraform init
      - terraform apply --auto-approve

artifacts:
  files:
    - "**/*"
