apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::039725305879:role/food-app-fargate-pod-execution-role-prod
      username: system:node:{{`{{SessionName}}`}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:node-proxier
    - rolearn: arn:aws:iam::039725305879:role/AdministratorRole
      username: admin
      groups:
        - system:masters
