apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: "{{ .Values.postgresHost }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresPort }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresPassword }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresDb }}"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"