apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.sslCertArn }}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: go-app
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  type: LoadBalancer
