apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
        - name: food-app-container
          image: 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com/food-app-ecr-repository-prod:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"