apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app-container
          image: 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com/food-app-ecr-repository-prod:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: "postgres-0.postgres-service.prod.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "yukihiro"
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "yukihiro"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
