version: 0.2

phases:
  pre_build:
    commands:
      - cd infra/terraform/aws/application/envs/${ENV}
      - sudo apt-get update && sudo apt-get install -y curl
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install

  build:
    commands:
      - terraform init
      - terraform apply -var="aws_profile=" -auto-approve

artifacts:
  files:
    - "**/*"
