version: 0.2

phases:
  pre_build:
    commands:
      - cd frontend

  build:
    commands:
      - npm run build
      - aws s3 sync build/ s3://food-app-frontend-bucket --delete

artifacts:
  files:
    - "**/*"
