version: 0.2

phases: 
  install:
    commands:
      - yum update -y
      - yum install -y postgresql

  build:
    commands:
      - cd infra/terraform/aws/application/envs/${ENV}
      - terraform init
      - terraform apply -var="aws_profile=" -auto-approve

artifacts:
  files:
    - "**/*"
