version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build
      - aws s3 sync build/ s3://food-app-frontend-bucket --delete

artifacts:
  files:
    - "**/*"
