version: 0.2

phases: 
  install:
    commands:
      - apk update
      - apk add postgresql-client

  build:
    commands:
      - cd infra/terraform/aws/application/envs/${ENV}
      - terraform init
      - terraform apply -var="aws_profile=" -auto-approve

artifacts:
  files:
    - "**/*"
