version: 0.2

phases:
  pre_build:
    commands:
      - cd backend

  build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker build -t food-app-ecr-repository-${ENV} .
      - docker tag food-app-ecr-repository-${ENV}:latest 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com/food-app-ecr-repository-${ENV}:latest
      - docker push 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com/food-app-ecr-repository-${ENV}:latest

artifacts:
  files:
    - "**/*"
