version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt-get update
      - apt-get install -y terraform
      - terraform -version

  pre_build:
    commands:
      - echo "Preparing environment..."
      - echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "Running Terraform commands..."
      - cd infra/terraform/aws/application/envs/${ENV}
      - terraform init
      - terraform apply -var="aws_profile=" -auto-approve
      - aws lambda invoke \
        --function-name "create_database-${ENV}" \
        --payload '{}' \
        response.json

artifacts:
  files:
    - "**/*"
