version: 0.2

phases:
  pre_build:
    commands:
      - cd infra/terraform/aws/environments/${ENV}

  build:
    commands:
      - terraform init
      - terraform apply -var="aws_profile=" -auto-approve

artifacts:
  files:
    - "**/*"
