version: 0.2


phases:
  pre_build:
    commands:
      - cd backend

  build:
    commands:
      - export POSTGRES_HOST=$(aws ssm get-parameter --name "/prod/rds_endpoint" --query "Parameter.Value" --output text)
      - export POSTGRES_USER=$(aws ssm get-parameter --name "/prod/db_username" --query "Parameter.Value" --output text)
      - export POSTGRES_PW=$(aws ssm get-parameter --name "/prod/db_password" --with-decryption --query "Parameter.Value" --output text)
      - export SECRET=$(aws ssm get-parameter --name "/prod/secret" --with-decryption --query "Parameter.Value" --output text)
      - |
        cat <<EOL > .env
        PORT=8080
        POSTGRES_USER=${POSTGRES_USER}
        POSTGRES_PW=${POSTGRES_PW}
        POSTGRES_DB=yukihiro
        POSTGRES_PORT=5432
        POSTGRES_HOST=${POSTGRES_HOST}
        SECRET=${SECRET}
        API_DOMAIN=api.food-app-generation.com
        FE_URL=https://food-app-generation.com
        EOL
      - echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com
      - aws ecr put-image-tag-mutability --repository-name food-app-ecr-repository-${ENV} --image-tag-mutability MUTABLE --region ap-northeast-1
      - docker build -t food-app-ecr-repository-${ENV} .
      - docker tag food-app-ecr-repository-${ENV}:latest 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com/food-app-ecr-repository-${ENV}:latest
      - docker push 039725305879.dkr.ecr.ap-northeast-1.amazonaws.com/food-app-ecr-repository-${ENV}:latest

artifacts:
  files:
    - "**/*"
