version: 0.2

phases:
  install:
    commands:
      - apk update && apk add curl
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - chmod +x ./aws/install
      - ./aws/install
      - aws --version

  build:
    commands:
      - cd infra/terraform/aws/application/envs/${ENV}
      - terraform init
      - terraform apply -var="aws_profile=" -auto-approve

artifacts:
  files:
    - "**/*"
