version: 0.2

phases:
  install:
    commands:
      - echo "Installing psql client"
      - sudo apt-get update -y
      - sudo apt-get install -y postgresql-client
      - echo "Installing kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "Installing aws-iam-authenticator"
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2021-01-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x aws-iam-authenticator
      - mv aws-iam-authenticator /usr/local/bin/
      - echo "Installing Helm"
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  pre_build:
    commands:
      - cd infra/terraform/aws/pipeline
      - echo "Authenticating with AWS EKS cluster"
      - aws eks update-kubeconfig --region ap-northeast-1 --name $CLUSTER_NAME
      - kubectl get namespace prod || kubectl create namespace prod
      - echo "Retrieving RDS endpoint from Parameter Store"
      - export POSTGRES_HOST=$(aws ssm get-parameter --name "/prod/rds_endpoint" --query "Parameter.Value" --output text)
      - export POSTGRES_USER="yukihiro"
      - export POSTGRES_PASSWORD="Yuki3769"
      - export POSTGRES_DB="yukihiro"
      - echo "Creating database if not exists"
      - |
        PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -tc "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'" | grep -q 1 || \
        PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -c "CREATE DATABASE $POSTGRES_DB;"

  build:
    commands:
      - echo "Deploying application to EKS with Helm"
      - helm upgrade --install go-app ./k8s --namespace prod --set postgresHost=$POSTGRES_HOST

  post_build:
    commands:
      - echo "Deployment complete"
